// Code generated by sdi. DO NOT EDIT.
package srvhttp

import "net/http"

// Deps returns a list of dependencies required by srv.
func (r *srv) Deps() []any {
	return []any{
		(*http.Handler)(nil),
	}
}

// Inject sets the dependencies for srv.
func (r *srv) Inject(args []any) {
	for _, arg := range args {
		switch v := arg.(type) {
		case http.Handler:
			r.handler = v
		}
	}
}
