// Code generated by sdi. DO NOT EDIT.
package srvhttp

// Deps returns a list of dependencies required by srv2.
func (r *srv2[T]) Deps() []any {
	return []any{
		(*T)(nil),
	}
}

// Inject sets the dependencies for srv2.
func (r *srv2[T]) Inject(args []any) {
	for _, arg := range args {
		switch v := arg.(type) {
		case T:
			r.Handler = v
		}
	}
}
